type: relationship-arc
characters:
  - "Luke Calloway"
  - "Raven Blackwood"

stages:
  early_partnership:
    description: >
      Luke and Raven start as partners out of necessity. Their contrasting styles create immediate tension—Luke values caution and planning, while Raven thrives on instinct and adaptability. They respect each other’s skills, but neither fully trusts the other yet.
    key_moments:
      - "First dive together: a near-failure due to miscommunication."
      - "A reluctant agreement to keep working together."
      - "Early training attempts show their differing approaches."

  deepening_trust:
    description: >
      Through repeated experiences, they begin to develop a real partnership. Trust builds in small ways—silent coordination in combat, Luke adapting to Raven’s fast decision-making, and Raven learning to trust his strategies.
    key_moments:
      - "A pivotal dungeon run where they succeed by blending their styles."
      - "An unexpected moment of vulnerability—Raven sees Luke hesitate for the first time."
      - "Luke, for the first time, follows Raven’s lead completely."

  emotional_turning_point:
    description: >
      The gala shifts their relationship. For the first time, they rely on each other outside of combat. The forced proximity and public setting push them into unfamiliar emotional territory. Luke realizes he enjoys being by Raven’s side in a way he hasn’t with anyone else. Raven, in turn, is unsettled by how easily she trusts him.
    key_moments:
      - "Raven uses Luke as an excuse to avoid unwanted attention."
      - "A dance that is both strategic and unexpectedly personal."
      - "A quiet conversation where they acknowledge their growing reliance on each other."

  conflict_and_rejection:
    description: >
      Raven, trying to define her own feelings, asks Luke to run the Radiant Spire with her—a reckless, impossible challenge. Luke immediately refuses, calling it dangerous, but in truth, he is afraid of losing her. His rejection wounds Raven deeply, and they separate emotionally.
    key_moments:
      - "Raven’s bold proposal."
      - "Luke’s rejection—logical on the surface but rooted in fear."
      - "Raven shutting down, distancing herself from him."

  rebuilding_trust:
    description: >
      Luke realizes the true reason he refused—his fear of loss, his tendency to always be the protector. He confronts this fear and asks for another chance, not just with the Spire, but with her. Raven, still hurt, tests him before agreeing to rebuild their trust.
    key_moments:
      - "Luke climbs to Raven’s window, proving he won’t run again."
      - "A direct, honest apology."
      - "A slow, deliberate agreement to build something real."

  final_partnership:
    description: >
      After months of training and learning to fully trust each other, they decide they are ready. When they enter the Spire, they do so as true equals—not just partners in combat, but in every sense. Their success hinges not just on skill, but on the absolute trust they have built.
    key_moments:
      - "One final test before they commit to the Spire."
      - "A wordless moment of understanding before the leap."
      - "The Heart of Light forcing them into a choice only they can make together."

narrative_purpose: >
  This relationship arc is about trust—not just in combat, but in each other. Luke’s journey is about learning that he doesn’t always have to be the protector; Raven’s is about allowing herself to rely on someone without feeling like she is losing herself. Their bond is tested repeatedly, but by the end, they choose each other, not out of necessity, but because they want to.